eval "$(starship init zsh)"

# Created by `pipx` on 2026-03-06 18:07:30
export PATH="$PATH:$HOME/.local/bin"

[ -f ~/.config/zsh/aliases.zsh ] && source ~/.config/zsh/aliases.zsh
[ -f ~/.config/zsh/functions.zsh ] && source ~/.config/zsh/functions.zsh

# Ollama endpoint for OpenCode
export LOCAL_ENDPOINT=http://localhost:11434/v1
